#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Sara Sun Botschon

# Short bio or description (displayed in the header)
description: Welcome to Sara Sun Botschon's Website!

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/66041664?s=400&u=1487e28e1b039bc63b54b585ffa44af171a592f6&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 
  facebook: 
  flickr:
  github: sarasunbotschon
  instagram: wangwangsun/
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: SBotschon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

title: "Trump Immigration Tweets WordCloud:"



# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
